### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by nettrom** [halfak/wikiclass#10]
README.md is not part of the PyPi tarball, so `pip install wikiclass` fails with an error.  Verified that the same issue is present when downloading the tarball then running `python setup.py install`.  Adding the README.md to the directory allows it to successfully install.

**Comment by halfak** [comment]
Fixed in 0.1.1.  I just pushed it to pypi.  Thanks for the report!

This was the issue: https://github.com/halfak/wikiclass/commit/365d2331e0dbe3ed6b742d18bd26cd4317bd4bce
