### ISSUE TITLE
Add an article assessment extractor

### ISSUE THREAD

**Issue by halfak** [halfak/wikiclass#7]
Something like this:

    Extracts article assessments from a Wikipedia XML dump.  
    
    Usage: 
        extract_assessments <dumpfile>... [--extractor=<classpath>]

Since assessments appear on an article's talk page in English Wikipedia, this script would not be able to determine what revision of an article a particular assessment was applied to.  It would write a TSV of rows containing:

* article_title -- The title of the assessed article
* talk_page_id -- The page_id of the talk page where the assessment appeared
* assessment -- The assessment class (e.g. Stub, Start, C, B, GA, A, FA)
* index -- The nth assessment the article has received
* start -- The timestamp of when the assessment started 
* end -- The timestamp of when the assessment ended

We'd need a post-processing script to be able to extract the revision ID that an assessment belongs to.  Something like this:

    Looks up the relevant article revision for the start of an assessment.

    Usage:
        lookup_assessments [--assessments=<path>] [--api=<url>]'

This would ultimately return the <rev_id> <assessment> pairs that  `revscoring extract_features` needs.

**Comment by nettrom** [comment]
For the latter part, there's some code in /data/project/suggestbot/projects/improved-qualpred/clean-training-set.py on Tool Labs that you could look at. To improve the classifier, we walk through the talk page history to find when a specific assessment changed, and then find the associated article revision ID. My code's quite messy, though.

**Comment by halfak** [comment]
This now exists.  See http://pythonhosted.org/wikiclass/utilities.html#module-wikiclass.utilities.extract_labelings
